#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
PARENT_DIR=$(cd "$REPO_ROOT/.." && pwd)   # außerhalb des Git-Repos
cd "$REPO_ROOT"

KEY_ALIAS="upload"
KS_DEFAULT="$PARENT_DIR/focusjournal-upload.jks"
PEM_FILE="$PARENT_DIR/focusjournal-upload-cert.pem"
SECRETS_FILE="$PARENT_DIR/focusjournal-signing-secrets.txt"
ENV_FILE="$REPO_ROOT/android/key.properties"

command -v keytool >/dev/null 2>&1 || { warn "keytool nicht gefunden — bitte ein JDK installieren."; exit 1; }
umask 077   # alles, was dieser Wizard anlegt, ist nur für dich lesbar

TOTAL_STAGES=5

banner "FocusJournal — Release-Keystore & Play-Paketnamen-Registrierung"

# ── Stage 1: Keystore erzeugen ────────────────────────────────────────────
stage "Release-Keystore erzeugen"
say "Der Keystore landet außerhalb des Git-Repos (im übergeordneten Ordner)."
ask storeFile "Pfad zum Keystore [Enter = $KS_DEFAULT]:"
KS_PATH="${storeFile:-$KS_DEFAULT}"
KS_PATH="${KS_PATH/#\~/$HOME}"

if [[ -f "$KS_PATH" ]]; then
  note "Keystore existiert bereits: $KS_PATH — er wird wiederverwendet, nichts wird überschrieben."
  ask_secret storePassword "Passwort des vorhandenen Keystores:"
  export FJ_STOREPASS="$storePassword"
  keytool -list -keystore "$KS_PATH" -alias "$KEY_ALIAS" -storepass:env FJ_STOREPASS >/dev/null \
    || { warn "Passwort falsch oder Alias '$KEY_ALIAS' fehlt — Abbruch."; exit 1; }
else
  while :; do
    ask_secret storePassword "Neues Keystore-Passwort (min. 6 Zeichen):"
    if (( ${#storePassword} < 6 )); then warn "Zu kurz — mindestens 6 Zeichen."; continue; fi
    ask_secret STOREPASS_REPEAT "Passwort wiederholen:"
    [[ "$storePassword" == "$STOREPASS_REPEAT" ]] && break
    warn "Passwörter stimmen nicht überein — bitte erneut."
  done
  ask CN_NAME "Name fürs Zertifikat (z. B. WariKoda) [Enter = WariKoda]:"
  CN_NAME="${CN_NAME:-WariKoda}"
  CN_NAME="${CN_NAME//,/ }"
  export FJ_STOREPASS="$storePassword"
  mkdir -p "$(dirname "$KS_PATH")"
  keytool -genkeypair -v -keystore "$KS_PATH" -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass:env FJ_STOREPASS -dname "CN=$CN_NAME"
  chmod 600 "$KS_PATH"
  say "${GREEN}✓${RESET} Keystore erzeugt: $KS_PATH (Alias: $KEY_ALIAS)"
fi
pause

# ── Stage 2: Fingerprint in der Play Console eintragen ────────────────────
stage "Öffentlichen Schlüssel in der Play Console eintragen"
FINGERPRINT=$(keytool -list -v -keystore "$KS_PATH" -alias "$KEY_ALIAS" -storepass:env FJ_STOREPASS \
  | grep -m1 'SHA256:' | sed 's/^[[:space:]]*//' || true)
[[ -n "$FINGERPRINT" ]] || { warn "Konnte den SHA-256-Fingerprint nicht auslesen — Abbruch."; exit 1; }
keytool -exportcert -rfc -keystore "$KS_PATH" -alias "$KEY_ALIAS" \
  -storepass:env FJ_STOREPASS -file "$PEM_FILE" >/dev/null
chmod 600 "$PEM_FILE"
say "Dein öffentlicher Schlüssel (SHA-256-Zertifikats-Fingerprint):"
printf '\n  %s%s%s\n\n' "$BOLD" "$FINGERPRINT" "$RESET"
note "Zusätzlich als PEM exportiert (falls die Console eine Datei will): $PEM_FILE"
step "Wechsle zur offenen Play-Console-Seite „Registrierung dieses Paketnamens abschließen“."
step "Trage dort den SHA-256-Fingerprint (Teil nach „SHA256:“) als öffentlichen Schlüssel ein."
open_url "https://play.google.com/console"
pause "Enter, wenn der Schlüssel in der Play Console eingetragen ist"

# ── Stage 3: key.properties + Secrets-Notiz schreiben ─────────────────────
stage "Signing-Konfiguration & Secrets-Notiz schreiben"
say "android/key.properties verdrahtet den Release-Build mit dem Keystore (gitignored)."
write_env storeFile "$KS_PATH"
write_env storePassword "$storePassword"
write_env keyAlias "$KEY_ALIAS"
write_env keyPassword "$storePassword"   # PKCS12: Key-Passwort = Store-Passwort
chmod 600 "$ENV_FILE"
{
  printf 'FocusJournal — Release-Signing-Secrets (%s)\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'NICHT in Git einchecken. Datei liegt bewusst außerhalb des Repos.\n\n'
  printf 'Keystore:          %s\n' "$KS_PATH"
  printf 'Key-Alias:         %s\n' "$KEY_ALIAS"
  printf 'Store-Passwort:    %s\n' "$storePassword"
  printf 'Key-Passwort:      %s (identisch, PKCS12)\n' "$storePassword"
  printf 'SHA-256:           %s\n' "${FINGERPRINT#SHA256: }"
  printf 'Public-Cert (PEM): %s\n' "$PEM_FILE"
  printf 'Paketname:         com.warikoda.focus_journal\n'
} > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
say "${GREEN}✓${RESET} Secrets-Notiz geschrieben: $SECRETS_FILE (nur für dich lesbar)"
pause

# ── Stage 4: GitHub-Actions-Secrets für signierte CI-Builds ───────────────
stage "GitHub-Actions-Secrets (CI) setzen"
say "Die CI (.github/workflows/build-apk.yml) signiert Release-APKs nur, wenn"
say "die Secrets KEYSTORE_BASE64, STORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD gesetzt sind."
if confirm "GitHub-Secrets jetzt über gh setzen?"; then
  set_secret KEYSTORE_BASE64 "$(base64 -w0 "$KS_PATH")"
  set_secret STORE_PASSWORD "$storePassword"
  set_secret KEY_ALIAS "$KEY_ALIAS"
  set_secret KEY_PASSWORD "$storePassword"
else
  SKIPPED+=("GitHub-Secrets KEYSTORE_BASE64, STORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD (CI baut sonst mit Wegwerf-Debug-Key)")
  note "Übersprungen — CI baut weiter mit einem Wegwerf-Debug-Key."
fi
pause

# ── Stage 5: Backup & Abschluss ───────────────────────────────────────────
stage "Backup & Abschluss"
warn "Keystore + Passwort SICHER sichern (Passwort-Manager, verschlüsseltes Backup)."
warn "Verlust = du kannst unter diesem Paketnamen nie wieder Updates signieren."
say "Zum Prüfen der Release-Signatur später:"
note "  flutter build apk --release"
note "  keytool -printcert -jarfile build/app/outputs/flutter-apk/app-release.apk"
note "Der SHA-256 dort muss dem in der Console eingetragenen entsprechen."
note "Google bestätigt die Paketnamen-Registrierung per E-Mail."
# ──────────────────────────────────────────────────────────────────────────

finish
